controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'login'

logout:
    path: /logout
